### ISSUE TITLE
Revisar CGI scripts y autoindex 

### ISSUE THREAD

**Issue by dtome-pe** [theonewhoknew/webserv#11]
El output de los cgis ni el autoindex se genera correctamente como html o el tipo que sea.

**Comment by dtome-pe** [comment]
Comprobamos que en el Mac no se detecta el pollhup cuando el proceso cgi acaba (siendo su EOF), si no que entra en POLLIN y se lee 0, vamos a intentar reformular.

**Comment by dtome-pe** [comment]
Arreglado el DELETE, ahora guardamos en variable buffer en receive lo leido, y no buffersize.

**Comment by jgravalo** [comment]
arreglado el autoindex. Ahora cuando busca la extensión pondrá directamente html si se ha iniciado una nueva variable autoindex.
