### ISSUE TITLE
Revisar Default Server

### ISSUE THREAD

**Issue by dtome-pe** [theonewhoknew/webserv#5]
Revisar que apliquemos correctamente este punto del subject:

The first server for a host:port will be the default for this host:port (that means
it will answer to all the requests that don’t belong to an other server).

Se entiende que es cumplir la ultima linea en el bloque de Setting Up Virtual Servers, en la pagina tuto de Nginx:

https://docs.nginx.com/nginx/admin-guide/web-server/web-server/#:~:text=The%20default%20server%20is%20the,a%20server%20as%20the%20default.

Seria retocar la funcion setServer en el constructor de Request, para cumplir con subject.

**Comment by jgravalo** [comment]
Según lo que he comprobado, lo cumplimos.

El test que hice fue 2 servers iguales con distintas carpetas de "upload_files" en el conf y llamar a upload.html, y se guardaba en el primer directorio mencionado.

Lo de la etiqueta default_server no lo tenemos que hacer en principio, lo pondría en el subject, digo yo vamos.
