### ISSUE TITLE
Comprobar Send/Write

### ISSUE THREAD

**Issue by dtome-pe** [theonewhoknew/webserv#8]
Desconectar a cliente a cualquier error de write/send y comprobar debidamente el resultado (0 y -1)

**Comment by dtome-pe** [comment]
send se encuentra en Cluster::run::writeTo::sendResponseAndReturnCode

**Comment by dtome-pe** [comment]
recv se encuentra en CLuster::run::readFrom::receive

**Comment by jgravalo** [comment]
send y recv/read protegidos
